{
  "openapi": "3.0.0",
  "info": {
    "title": "CROWD",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "http://127.0.0.1:9000"
    }
  ],
  "components": {
    "securitySchemes": {
      "noauthAuth": {
        "type": "http",
        "scheme": "noauth"
      }
    }
  },
  "tags": [
    {
      "name": "User Manager"
    },
    {
      "name": "Task Manager"
    },
    {
      "name": "Stream Manager"
    },
    {
      "name": "Notification Manager"
    }
  ],
  "paths": {
    "/user/signup": {
      "post": {
        "tags": [
          "User Manager"
        ],
        "summary": "signup",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "first_name": "sara",
                  "last_name": "safaee",
                  "user_role": "WORKER",
                  "phone": "0992246",
                  "email": "sarasafaeeW@gmail.com",
                  "password": "123456",
                  "location": "IRAN"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "InsertedID": "637882b15e1d5175a1c03831"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/user/login": {
      "post": {
        "tags": [
          "User Manager"
        ],
        "summary": "login",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "email": "ADMIN@gmail.com",
                  "password": "ADMINADMIN"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "ID": "637882b15e1d5175a1c03831",
                    "first_name": "sara",
                    "last_name": "safaee",
                    "Password": "$2a$14$9hlggNcijuEDrGOrWEKjb.bXccTEoEwCk6v2wm3xF7yLA/IXQwTx6",
                    "email": "sarasafaeeW@gmail.com",
                    "phone": "0992246",
                    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6InNhcmFzYWZhZWVXQGdtYWlsLmNvbSIsIkZpcnN0X25hbWUiOiJzYXJhIiwiTGFzdF9uYW1lIjoic2FmYWVlIiwiVWlkIjoiNjM3ODgyYjE1ZTFkNTE3NWExYzAzODMxIiwiVXNlcl9yb2xlIjoiV09SS0VSIiwiZXhwIjoxNjY4OTI4NjQ3fQ.cLvEiA7MQDUThs3-20xkrtCcACsZBkaCK2PfAfmN4dY",
                    "User_role": "WORKER",
                    "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6IiIsIkZpcnN0X25hbWUiOiIiLCJMYXN0X25hbWUiOiIiLCJVaWQiOiIiLCJVc2VyX3JvbGUiOiIiLCJleHAiOjE2Njk0NDcwNDd9.C_D7hStTphls_cSknfpZd2zApVndMLEMGsA6d7tNsgI",
                    "created_at": "2022-11-19T07:16:01Z",
                    "updated_at": "2022-11-19T07:17:27Z",
                    "user_id": "637882b15e1d5175a1c03831",
                    "location": "IRAN"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/users": {
      "get": {
        "tags": [
          "User Manager"
        ],
        "summary": "GetUsers",
        "parameters": [
          {
            "name": "token",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6IkFETUlOQGdtYWlsLmNvbSIsIkZpcnN0X25hbWUiOiJBZG1pbiIsIkxhc3RfbmFtZSI6IkFkbWluIiwiVWlkIjoiNjM1NTNjMjEzY2ZlY2Q1NmQ1Y2Q0YWRkIiwiVXNlcl9yb2xlIjoiQURNSU4iLCJleHAiOjE2Njg4ODk3MDJ9.HBDd5EJDDwWfoonbhfSZoP06yQ9Xj1k326NIxXUd3JY"
          },
          {
            "name": "recordPerPage",
            "in": "header",
            "schema": {
              "type": "integer"
            },
            "example": "3"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "total_count": 15,
                    "user_items": [
                      {
                        "_id": "63553c0e3cfecd56d5cd4adc",
                        "created_at": "2022-10-23T16:35:18+03:30",
                        "email": "ADMIN2@gmail.com",
                        "first_name": "Admin",
                        "last_name": "Admin",
                        "password": "$2a$14$oNODn5KpR4i0Vdqqxh2IeuKmgfBz1XWAu7AumPh88IBfEFPDRaUhC",
                        "phone": "000000000000000002",
                        "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6IiIsIkZpcnN0X25hbWUiOiIiLCJMYXN0X25hbWUiOiIiLCJVaWQiOiIiLCJVc2VyX3JvbGUiOiIiLCJleHAiOjE2NjcxMzUxMTh9.gZeLPJ5434sjBX42G7gQyFijcafpAsAcGdOFBPgGSSw",
                        "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6IkFETUlOMkBnbWFpbC5jb20iLCJGaXJzdF9uYW1lIjoiQWRtaW4iLCJMYXN0X25hbWUiOiJBZG1pbiIsIlVpZCI6IjYzNTUzYzBlM2NmZWNkNTZkNWNkNGFkYyIsIlVzZXJfcm9sZSI6IkFETUlOIiwiZXhwIjoxNjY2NjE2NzE4fQ.Yvf7J8FWOkP-ExfF64M1dQ-l5PEsIMUTgO_AYPHicM0",
                        "updated_at": "2022-10-23T16:35:18+03:30",
                        "user_id": "63553c0e3cfecd56d5cd4adc",
                        "user_role": "ADMIN"
                      },
                      {
                        "_id": "63553c213cfecd56d5cd4add",
                        "created_at": "2022-10-23T16:35:37+03:30",
                        "email": "ADMIN@gmail.com",
                        "first_name": "Admin",
                        "last_name": "Admin",
                        "password": "$2a$14$LBb4zaLKK5.LPFZGjEdguO4Fbg9i1wGIfx1VKVcAQqTQmQGIND6ty",
                        "phone": "000000000000000001",
                        "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6IiIsIkZpcnN0X25hbWUiOiIiLCJMYXN0X25hbWUiOiIiLCJVaWQiOiIiLCJVc2VyX3JvbGUiOiIiLCJleHAiOjE2Njk0MDg1OTN9.fNoQjJVtaKUOGVxTcZaczEW7yWpkiYfCr0zQ6xeatLQ",
                        "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6IkFETUlOQGdtYWlsLmNvbSIsIkZpcnN0X25hbWUiOiJBZG1pbiIsIkxhc3RfbmFtZSI6IkFkbWluIiwiVWlkIjoiNjM1NTNjMjEzY2ZlY2Q1NmQ1Y2Q0YWRkIiwiVXNlcl9yb2xlIjoiQURNSU4iLCJleHAiOjE2Njg4OTAxOTN9.Ul7Br-ZtWQJY2HdOezi6wAGMQiyF3_kv8LyNpK0lyRo",
                        "updated_at": "2022-11-19T00:06:33+03:30",
                        "user_id": "63553c213cfecd56d5cd4add",
                        "user_role": "ADMIN"
                      },
                      {
                        "_id": "63553cec536113f20a9a28ae",
                        "created_at": "2022-10-23T16:39:00+03:30",
                        "email": "saraW@gmail.com",
                        "first_name": "sara",
                        "last_name": "safaee",
                        "password": "$2a$14$UjuR49gwPKcpSkaETJlw6OcHp9Eow0gIR.eB4PBC.Cpg.BWIVjg.W",
                        "phone": "123",
                        "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6IiIsIkZpcnN0X25hbWUiOiIiLCJMYXN0X25hbWUiOiIiLCJVaWQiOiIiLCJVc2VyX3JvbGUiOiIiLCJleHAiOjE2NjkzODA1ODB9.1S0QE0GxQEW8o9OvwLB8tAx9ceNiFXxdE7sBizOPVNk",
                        "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6InNhcmFXQGdtYWlsLmNvbSIsIkZpcnN0X25hbWUiOiJzYXJhIiwiTGFzdF9uYW1lIjoic2FmYWVlIiwiVWlkIjoiNjM1NTNjZWM1MzYxMTNmMjBhOWEyOGFlIiwiVXNlcl9yb2xlIjoiV09SS0VSIiwiZXhwIjoxNjY4ODYyMTgwfQ.CS6jlFXQ1BvmBVYf1xdE8NlITE0HYafzUhjPUDXj_9o",
                        "updated_at": "2022-11-18T16:19:40+03:30",
                        "user_id": "63553cec536113f20a9a28ae",
                        "user_role": "WORKER"
                      },
                      {
                        "_id": "63553cff536113f20a9a28af",
                        "created_at": "2022-10-23T16:39:19+03:30",
                        "email": "saraR@gmail.com",
                        "first_name": "sara",
                        "last_name": "safaee",
                        "password": "$2a$14$PRzNY4O82btgSojuI/SqRuOyHuBjJ7u7QbbGMSaNYIF5XlGwTQtJ6",
                        "phone": "124",
                        "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6IiIsIkZpcnN0X25hbWUiOiIiLCJMYXN0X25hbWUiOiIiLCJVaWQiOiIiLCJVc2VyX3JvbGUiOiIiLCJleHAiOjE2Njk0MDgwNjJ9.xGUJ_eLkqbBeQYvIbU7HHAugqfYirhijctUnc-cxsBY",
                        "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6InNhcmFSQGdtYWlsLmNvbSIsIkZpcnN0X25hbWUiOiJzYXJhIiwiTGFzdF9uYW1lIjoic2FmYWVlIiwiVWlkIjoiNjM1NTNjZmY1MzYxMTNmMjBhOWEyOGFmIiwiVXNlcl9yb2xlIjoiUkVRVUVTVEVSIiwiZXhwIjoxNjY4ODg5NjYyfQ.RiGRs--RiyEKmAJOxLDqh1CKVEsVIRd9qzqbdzu8CYw",
                        "updated_at": "2022-11-18T23:57:42+03:30",
                        "user_id": "63553cff536113f20a9a28af",
                        "user_role": "REQUESTER"
                      },
                      {
                        "_id": "63554c376fb451f6c49eed73",
                        "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6IiIsIkZpcnN0X25hbWUiOiIiLCJMYXN0X25hbWUiOiIiLCJVaWQiOiIiLCJVc2VyX3JvbGUiOiIifQ.dB2eEzCiljFmRZcDChMy0An6QGYI4sebEt1AjXwTSEg",
                        "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6IiIsIkZpcnN0X25hbWUiOiIiLCJMYXN0X25hbWUiOiIiLCJVaWQiOiIiLCJVc2VyX3JvbGUiOiIifQ.dB2eEzCiljFmRZcDChMy0An6QGYI4sebEt1AjXwTSEg",
                        "updated_at": "2022-10-23T17:50:41+03:30",
                        "user_id": ""
                      },
                      {
                        "_id": "635641ceaf6a21f425599292",
                        "created_at": "2022-10-24T11:12:06+03:30",
                        "email": "saraR1@gmail.com",
                        "first_name": "sara",
                        "last_name": "safaee",
                        "password": "$2a$14$MhfzAFXIeD8BXS23lzzFOeBBEZGORAjz8FlMoEC8eN/D6jYzyH.56",
                        "phone": "1245",
                        "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6IiIsIkZpcnN0X25hbWUiOiIiLCJMYXN0X25hbWUiOiIiLCJVaWQiOiIiLCJVc2VyX3JvbGUiOiIiLCJleHAiOjE2NjkxMTU2MjF9.UZNFASOyYMolaXvJhtWyK6Q3mANQRZLcSdvZg-2vuGM",
                        "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6InNhcmFSMUBnbWFpbC5jb20iLCJGaXJzdF9uYW1lIjoic2FyYSIsIkxhc3RfbmFtZSI6InNhZmFlZSIsIlVpZCI6IjYzNTY0MWNlYWY2YTIxZjQyNTU5OTI5MiIsIlVzZXJfcm9sZSI6IlJFUVVFU1RFUiIsImV4cCI6MTY2ODU5NzIyMX0.4WNzBWgbfEfQiIAewF35Qz_9RFckU86FwyBhyB36-S0",
                        "updated_at": "2022-11-15T14:43:41+03:30",
                        "user_id": "635641ceaf6a21f425599292",
                        "user_role": "REQUESTER"
                      },
                      {
                        "_id": "63566ce0310e288624e63b28",
                        "created_at": "2022-10-24T14:15:52+03:30",
                        "email": "saraWW@gmail.com",
                        "first_name": "sfwef",
                        "last_name": "safaee",
                        "password": "$2a$14$xuBXDjcaaTLMO27bL6TJJO/iVIxcLkRVukzM.oJJ0Jp5gzlgnQzkW",
                        "phone": "124567",
                        "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6IiIsIkZpcnN0X25hbWUiOiIiLCJMYXN0X25hbWUiOiIiLCJVaWQiOiIiLCJVc2VyX3JvbGUiOiIiLCJleHAiOjE2NjcyMTkyMjh9.Zv-i6PANpxW0Tl039O2JHpoCaYyOZM-0RSmzZiswNDI",
                        "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6InNhcmFXMUBnbWFpbC5jb20iLCJGaXJzdF9uYW1lIjoieml6aTIiLCJMYXN0X25hbWUiOiJzYWZhZWUiLCJVaWQiOiI2MzU2NmNlMDMxMGUyODg2MjRlNjNiMjgiLCJVc2VyX3JvbGUiOiJXT1JLRVIiLCJleHAiOjE2NjY3MDA4Mjh9.D1LeuRFY6NBcdz-jgTfC7CSK9bKJizeViH6XzaOV3jE",
                        "updated_at": "2022-10-24T15:57:08+03:30",
                        "user_id": "63566ce0310e288624e63b28",
                        "user_role": "WORKER"
                      },
                      {
                        "_id": "635677fc92febd255fa68dba",
                        "created_at": "2022-10-24T15:03:16+03:30",
                        "email": "saraW2@gmail.com",
                        "first_name": "sara",
                        "last_name": "safaee",
                        "password": "$2a$14$QIabY643EPV49EShVxGq..7B4b5M.MTQneP0ALwUVRqbo.4cuDnbK",
                        "phone": "1245678",
                        "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6IiIsIkZpcnN0X25hbWUiOiIiLCJMYXN0X25hbWUiOiIiLCJVaWQiOiIiLCJVc2VyX3JvbGUiOiIiLCJleHAiOjE2NjcyMjM0OTh9.rtbzBrGYvXkWmsfgbU1Mb3tAY5mb1_QZks6sXOqsPWs",
                        "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6InNhcmFXMkBnbWFpbC5jb20iLCJGaXJzdF9uYW1lIjoic2FyYSIsIkxhc3RfbmFtZSI6InNhZmFlZSIsIlVpZCI6IjYzNTY3N2ZjOTJmZWJkMjU1ZmE2OGRiYSIsIlVzZXJfcm9sZSI6IldPUktFUiIsImV4cCI6MTY2NjcwNTA5OH0.78CTl8n9sh1RMj6apzUklHQzgNrof0XsxMxEjnnRtkE",
                        "updated_at": "2022-10-24T17:08:18+03:30",
                        "user_id": "635677fc92febd255fa68dba",
                        "user_role": "WORKER"
                      },
                      {
                        "_id": "63579d59b3cab9abd9cf782a",
                        "created_at": "2022-10-25T11:54:57+03:30",
                        "email": "saraRR@gmail.com",
                        "first_name": "sara",
                        "last_name": "safaee",
                        "password": "$2a$14$X9nLOfzYfsOILBzCcVdCgegTZChX3Ax4FfggnB0ZwQvUnIiVKd68G",
                        "phone": "12456789",
                        "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6IiIsIkZpcnN0X25hbWUiOiIiLCJMYXN0X25hbWUiOiIiLCJVaWQiOiIiLCJVc2VyX3JvbGUiOiIiLCJleHAiOjE2NjcyOTExMTh9.u2Lm3uf3Dzm5mL9F2NyN5Qvc0T12l_kJygIwn9FsVg4",
                        "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6InNhcmFSUkBnbWFpbC5jb20iLCJGaXJzdF9uYW1lIjoic2FyYSIsIkxhc3RfbmFtZSI6InNhZmFlZSIsIlVpZCI6IjYzNTc5ZDU5YjNjYWI5YWJkOWNmNzgyYSIsIlVzZXJfcm9sZSI6IlJFUVVFU1RFUiIsImV4cCI6MTY2Njc3MjcxOH0.dhnA9UEGUH1oY4HlSQjziQEBPqX9xlAZ_MUJ-c_mXUo",
                        "updated_at": "2022-10-25T11:55:18+03:30",
                        "user_id": "63579d59b3cab9abd9cf782a",
                        "user_role": "REQUESTER"
                      },
                      {
                        "_id": "6357cc2aed0d871705269bfb",
                        "created_at": "2022-10-25T15:14:42+03:30",
                        "email": "saraRR1@gmail.com",
                        "first_name": "sara",
                        "last_name": "safaee",
                        "password": "$2a$14$rtBzPsVYNN1EZjzCFjixaON277y3zrggXG3ZtJyfQhz.qRe3luX9u",
                        "phone": "1245111",
                        "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6IiIsIkZpcnN0X25hbWUiOiIiLCJMYXN0X25hbWUiOiIiLCJVaWQiOiIiLCJVc2VyX3JvbGUiOiIiLCJleHAiOjE2NjczMDMwODh9.yNRfEiPo-aUzqVHNAAhFezjH5lo5tAKIXR6gmVR6iGw",
                        "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6InNhcmFSUjFAZ21haWwuY29tIiwiRmlyc3RfbmFtZSI6InNhcmEiLCJMYXN0X25hbWUiOiJzYWZhZWUiLCJVaWQiOiI2MzU3Y2MyYWVkMGQ4NzE3MDUyNjliZmIiLCJVc2VyX3JvbGUiOiJSRVFVRVNURVIiLCJleHAiOjE2NjY3ODQ2ODh9.qGVcU5n7DzN1cHKSfdJtHzc3W78yVR84TduUczgk0SY",
                        "updated_at": "2022-10-25T15:14:48+03:30",
                        "user_id": "6357cc2aed0d871705269bfb",
                        "user_role": "REQUESTER"
                      }
                    ]
                  }
                }
              }
            }
          }
        }
      }
    },
    "/user/logout": {
      "post": {
        "tags": [
          "User Manager"
        ],
        "summary": "logout",
        "requestBody": {
          "content": {}
        },
        "parameters": [
          {
            "name": "token",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6InNhcmFzYWZhZWVXQGdtYWlsLmNvbSIsIkZpcnN0X25hbWUiOiJzYXJhIiwiTGFzdF9uYW1lIjoic2FmYWVlIiwiVWlkIjoiNjM3N2VhNjI2ZDQ3Y2YwNjdhOWU4ZWQ3IiwiVXNlcl9yb2xlIjoiV09SS0VSIiwiZXhwIjoxNjY4ODg5NzE2fQ.UKJeavt56fY5LpQexzT45oaU61oJapOFS9vqVhKuj00"
          }
        ],
        "responses": {
          "500": {
            "description": null,
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "error": "you already logedOut"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/user/deactive": {
      "delete": {
        "tags": [
          "User Manager"
        ],
        "summary": "DeleteUser",
        "parameters": [
          {
            "name": "token",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6InNhcmFXMUBnbWFpbC5jb20iLCJGaXJzdF9uYW1lIjoic2FyYSIsIkxhc3RfbmFtZSI6InNhZmFlZSIsIlVpZCI6IjYzNTY1YzNlNjQxYmY4MDU5NmU5ODQ4NyIsIlVzZXJfcm9sZSI6IlJFUVVFU1RFUiIsImV4cCI6MTY2NjY5MDQ5OX0.7ukzf9pKe__hUIvvG95jb2XdfPFIsAYyabHe54o4bvY"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "DeletedCount": 1
                  }
                }
              }
            }
          }
        }
      }
    },
    "/user/63566ce0310e288624e63b28": {
      "put": {
        "tags": [
          "User Manager"
        ],
        "summary": "EditUser",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "email": "saraWWmail.com",
                  "User_role": "WORKEfddd"
                }
              }
            }
          }
        },
        "parameters": [
          {
            "name": "token",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6IkFETUlOQGdtYWlsLmNvbSIsIkZpcnN0X25hbWUiOiJBZG1pbiIsIkxhc3RfbmFtZSI6IkFkbWluIiwiVWlkIjoiNjM1NTNjMjEzY2ZlY2Q1NmQ1Y2Q0YWRkIiwiVXNlcl9yb2xlIjoiQURNSU4iLCJleHAiOjE2Njg4OTAxOTN9.Ul7Br-ZtWQJY2HdOezi6wAGMQiyF3_kv8LyNpK0lyRo"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "ID": "637885085e1d5175a1c03834",
                    "first_name": "sara",
                    "last_name": "safaee",
                    "Password": "$2a$14$etYJ88qQuc00qMJO13AC0uFIKPLtfxfC0sWTCRQ/p6SpvdQXRkM5m",
                    "email": "sarasafaeeWW@gmail.com",
                    "phone": "0992246",
                    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6InNhcmFzYWZhZWVXQGdtYWlsLmNvbSIsIkZpcnN0X25hbWUiOiJzYXJhIiwiTGFzdF9uYW1lIjoic2FmYWVlIiwiVWlkIjoiNjM3ODg1MDg1ZTFkNTE3NWExYzAzODM0IiwiVXNlcl9yb2xlIjoiV09SS0VSIiwiZXhwIjoxNjY4OTI5MTY1fQ.m4jCsf4pAC4gBfg4dGC9W5IOFiz250BHLE7r8hakMyc",
                    "User_role": "WORKER",
                    "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6IiIsIkZpcnN0X25hbWUiOiIiLCJMYXN0X25hbWUiOiIiLCJVaWQiOiIiLCJVc2VyX3JvbGUiOiIiLCJleHAiOjE2Njk0NDc1NjV9.Yom_R4kQtNnhi3tz-bS5GZNPzuNV-EdFPfnGiyLpqqc",
                    "created_at": "2022-11-19T07:26:00Z",
                    "updated_at": "2022-11-19T10:57:20+03:30",
                    "user_id": "637885085e1d5175a1c03834",
                    "location": "IRAN"
                  }
                }
              }
            }
          }
        }
      },
      "get": {
        "tags": [
          "User Manager"
        ],
        "summary": "GetUser",
        "parameters": [
          {
            "name": "token",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6InNhcmFzYWZhZWVXQGdtYWlsLmNvbSIsIkZpcnN0X25hbWUiOiJzYXJhIiwiTGFzdF9uYW1lIjoic2FmYWVlIiwiVWlkIjoiNjM3N2VhNjI2ZDQ3Y2YwNjdhOWU4ZWQ3IiwiVXNlcl9yb2xlIjoiV09SS0VSIiwiZXhwIjoxNjY4ODg5NzE2fQ.UKJeavt56fY5LpQexzT45oaU61oJapOFS9vqVhKuj00"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "ID": "637885085e1d5175a1c03834",
                    "first_name": "sara",
                    "last_name": "safaee",
                    "Password": "$2a$14$etYJ88qQuc00qMJO13AC0uFIKPLtfxfC0sWTCRQ/p6SpvdQXRkM5m",
                    "email": "sarasafaeeWW@gmail.com",
                    "phone": "0992246",
                    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6InNhcmFzYWZhZWVXQGdtYWlsLmNvbSIsIkZpcnN0X25hbWUiOiJzYXJhIiwiTGFzdF9uYW1lIjoic2FmYWVlIiwiVWlkIjoiNjM3ODg1MDg1ZTFkNTE3NWExYzAzODM0IiwiVXNlcl9yb2xlIjoiV09SS0VSIiwiZXhwIjoxNjY4OTI5MTY1fQ.m4jCsf4pAC4gBfg4dGC9W5IOFiz250BHLE7r8hakMyc",
                    "User_role": "WORKER",
                    "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6IiIsIkZpcnN0X25hbWUiOiIiLCJMYXN0X25hbWUiOiIiLCJVaWQiOiIiLCJVc2VyX3JvbGUiOiIiLCJleHAiOjE2Njk0NDc1NjV9.Yom_R4kQtNnhi3tz-bS5GZNPzuNV-EdFPfnGiyLpqqc",
                    "created_at": "2022-11-19T07:26:00Z",
                    "updated_at": "2022-11-19T07:27:20Z",
                    "user_id": "637885085e1d5175a1c03834",
                    "location": "IRAN"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/task": {
      "post": {
        "tags": [
          "Task Manager"
        ],
        "summary": "CtreateTask",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "title": "school0",
                  "max_workers": 10,
                  "approve_on_demand": true,
                  "stream_id": "6374cadd28fcffdd26a1617f",
                  "deadline": "2023-10-25T08:55:00.000+00:00"
                }
              }
            }
          }
        },
        "parameters": [
          {
            "name": "token",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6InNhcmFSQGdtYWlsLmNvbSIsIkZpcnN0X25hbWUiOiJzYXJhIiwiTGFzdF9uYW1lIjoic2FmYWVlIiwiVWlkIjoiNjM1NTNjZmY1MzYxMTNmMjBhOWEyOGFmIiwiVXNlcl9yb2xlIjoiUkVRVUVTVEVSIiwiZXhwIjoxNjY4Njg0ODU2fQ.5yFyfMShLWWHCmRd9NyfAxC46LIte7Ar4vmRep9ZtX0"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "InsertedID": "637886bf5e1d5175a1c03836"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/tasks/customized": {
      "get": {
        "tags": [
          "Task Manager"
        ],
        "summary": "GetCustomizedTasks",
        "parameters": [
          {
            "name": "token",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6InNhcmFXQGdtYWlsLmNvbSIsIkZpcnN0X25hbWUiOiJzYXJhIiwiTGFzdF9uYW1lIjoic2FmYWVlIiwiVWlkIjoiNjM1NTNjZWM1MzYxMTNmMjBhOWEyOGFlIiwiVXNlcl9yb2xlIjoiV09SS0VSIiwiZXhwIjoxNjY4Nzk0NzMwfQ.g6AgXDHd2Dw8w2OxKRnmkboO3wBjFnoExr4spNS3MQw"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "total_count": 1,
                    "user_items": [
                      {
                        "_id": "6357a46433a2308757b0c9f9",
                        "approve_on_demand": false,
                        "created_at": "2022-10-25T12:25:00+03:30",
                        "deadline": "0001-01-01T03:30:00+03:30",
                        "description": null,
                        "filter": [],
                        "max_workers": "5",
                        "requester_id": "1456988",
                        "stream_id": "123456321",
                        "task_id": "6357a46433a2308757b0c9f9",
                        "title": "garden",
                        "updated_at": "2022-10-25T12:25:00+03:30",
                        "wage": null
                      }
                    ]
                  }
                }
              }
            }
          }
        }
      }
    },
    "/task/6357c0f051d46b81948c71df": {
      "put": {
        "tags": [
          "Task Manager"
        ],
        "summary": "EditTask",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "max_workers": 64
                }
              }
            }
          }
        },
        "parameters": [
          {
            "name": "token",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6InNhcmFSMTU4QGdtYWlsLmNvbSIsIkZpcnN0X25hbWUiOiJzYXJhIiwiTGFzdF9uYW1lIjoic2FmYWVlIiwiVWlkIjoiNjM1N2Y5NmVmNDkyNmQyZDg2ZDU5MmIzIiwiVXNlcl9yb2xlIjoiUkVRVUVTVEVSIiwiZXhwIjoxNjY2OTQ2MDE4fQ.VVE-NlZpYwp7L7ZSnxTy3y3Gq67IpjugUPFr-5jQt_k"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "ID": "637886bf5e1d5175a1c03836",
                    "max_workers": 64,
                    "title": "school0",
                    "Description": null,
                    "approve_on_demand": true,
                    "deadline": "2023-10-25T08:55:00Z",
                    "Wage": null,
                    "stream_id": "637886ad5e1d5175a1c03835",
                    "requester_id": "63553cff536113f20a9a28af",
                    "created_at": "2022-11-19T07:33:19Z",
                    "updated_at": "2022-11-19T11:08:02+03:30",
                    "task_id": "637886bf5e1d5175a1c03836"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/task/filter": {
      "post": {
        "tags": [
          "Task Manager"
        ],
        "summary": "CreateFilterTask",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "task_id": "636e0b4b58647128f1d1b61c",
                  "tags": [
                    "GERMANY",
                    "ITALY",
                    "INDI"
                  ]
                }
              }
            }
          }
        },
        "parameters": [
          {
            "name": "token",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6InNhcmFSQGdtYWlsLmNvbSIsIkZpcnN0X25hbWUiOiJzYXJhIiwiTGFzdF9uYW1lIjoic2FmYWVlIiwiVWlkIjoiNjM1NTNjZmY1MzYxMTNmMjBhOWEyOGFmIiwiVXNlcl9yb2xlIjoiUkVRVUVTVEVSIiwiZXhwIjoxNjY4MjM2MTM3fQ.he8mJHlAZYX2LQ1S0Z5F4yv3xTvPoXw0vawEE-W7FI0"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "InsertedID": "637888275e1d5175a1c03837"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/task/filter/635a4aa4fd47b436bb5df2ef": {
      "get": {
        "tags": [
          "Task Manager"
        ],
        "summary": "GetFilterTaskByID",
        "parameters": [
          {
            "name": "token",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6IkFETUlOQGdtYWlsLmNvbSIsIkZpcnN0X25hbWUiOiJBZG1pbiIsIkxhc3RfbmFtZSI6IkFkbWluIiwiVWlkIjoiNjM1NTNjMjEzY2ZlY2Q1NmQ1Y2Q0YWRkIiwiVXNlcl9yb2xlIjoiQURNSU4iLCJleHAiOjE2NjgwOTkwMDl9.TKGAtL2z4qxJQFpYQ1xQEqkZevLi5r6h4PNfkFRf808"
          }
        ],
        "responses": {
          "200": {
            "description": null,
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "ID": "637888275e1d5175a1c03837",
                    "tags": [
                      "GERMANY",
                      "ITALY",
                      "INDI"
                    ],
                    "created_at": "2022-11-19T07:39:19Z",
                    "updated_at": "2022-11-19T07:39:19Z",
                    "task_id": "637886bf5e1d5175a1c03836",
                    "filter_task_id": "637888275e1d5175a1c03837"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/task/filtertask/635a4aa4fd47b436bb5df2ef": {
      "get": {
        "tags": [
          "Task Manager"
        ],
        "summary": "GetFilterTaskByTaskID",
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/task/filter/637888275e1d5175a1c03837": {
      "put": {
        "tags": [
          "Task Manager"
        ],
        "summary": "EditFilterTask",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "tags": [
                    "IRAN",
                    "ITALY",
                    "INDIA"
                  ],
                  "task_id": "12345"
                }
              }
            }
          }
        },
        "parameters": [
          {
            "name": "token",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6IiIsIkZpcnN0X25hbWUiOiIiLCJMYXN0X25hbWUiOiIiLCJVaWQiOiIiLCJVc2VyX3JvbGUiOiIiLCJleHAiOjE2Njg2OTc3NzZ9.eN4VII5gcV8eb71wuJb_Vn3cuckNq79Lincmb8I9rQQ"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "ID": "637888275e1d5175a1c03837",
                    "tags": [
                      "IRAN",
                      "ITALY",
                      "INDIA"
                    ],
                    "created_at": "2022-11-19T07:39:19Z",
                    "updated_at": "2022-11-19T11:21:48+03:30",
                    "task_id": "637886bf5e1d5175a1c03836",
                    "filter_task_id": "637888275e1d5175a1c03837"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/task/6357f991f4926d2d86d592b4": {
      "delete": {
        "tags": [
          "Task Manager"
        ],
        "summary": "DeleteTask",
        "parameters": [
          {
            "name": "token",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6InNhcmFSQGdtYWlsLmNvbSIsIkZpcnN0X25hbWUiOiJzYXJhIiwiTGFzdF9uYW1lIjoic2FmYWVlIiwiVWlkIjoiNjM1NTNjZmY1MzYxMTNmMjBhOWEyOGFmIiwiVXNlcl9yb2xlIjoiUkVRVUVTVEVSIiwiZXhwIjoxNjY4MjQwMTg4fQ.RMjbdAz0ZUg2trGAWAchmANUYQ7OuHY3S3S34K-TFWk"
          }
        ],
        "responses": {
          "500": {
            "description": null,
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "error": " no documents in result"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/task/filter/636df3a119f1020d7b43e5f4": {
      "delete": {
        "tags": [
          "Task Manager"
        ],
        "summary": "DeleteFilterTask",
        "parameters": [
          {
            "name": "token",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6InNhcmFSQGdtYWlsLmNvbSIsIkZpcnN0X25hbWUiOiJzYXJhIiwiTGFzdF9uYW1lIjoic2FmYWVlIiwiVWlkIjoiNjM1NTNjZmY1MzYxMTNmMjBhOWEyOGFmIiwiVXNlcl9yb2xlIjoiUkVRVUVTVEVSIiwiZXhwIjoxNjY4MjM2NTE5fQ.XgBMFV8BsblT8m3v-OML1GlIXwrMgpZOcVX-7MReVXs"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "error": " no documents in result"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/task/application/6374cb0f28fcffdd26a16180": {
      "post": {
        "tags": [
          "Task Manager"
        ],
        "summary": "ApplyTask",
        "requestBody": {
          "content": {}
        },
        "parameters": [
          {
            "name": "token",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6InNhcmFXQGdtYWlsLmNvbSIsIkZpcnN0X25hbWUiOiJzYXJhIiwiTGFzdF9uYW1lIjoic2FmYWVlIiwiVWlkIjoiNjM1NTNjZWM1MzYxMTNmMjBhOWEyOGFlIiwiVXNlcl9yb2xlIjoiV09SS0VSIiwiZXhwIjoxNjY4Nzk0NzMwfQ.g6AgXDHd2Dw8w2OxKRnmkboO3wBjFnoExr4spNS3MQw"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "InsertedID": "63788cdd5e1d5175a1c03838"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/task/evaluation/6374cb3f28fcffdd26a16181": {
      "put": {
        "tags": [
          "Task Manager"
        ],
        "summary": "EvaluateWorkerTask",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "last_status": "DOING"
                }
              }
            }
          }
        },
        "parameters": [
          {
            "name": "token",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6InNhcmFSQGdtYWlsLmNvbSIsIkZpcnN0X25hbWUiOiJzYXJhIiwiTGFzdF9uYW1lIjoic2FmYWVlIiwiVWlkIjoiNjM1NTNjZmY1MzYxMTNmMjBhOWEyOGFmIiwiVXNlcl9yb2xlIjoiUkVRVUVTVEVSIiwiZXhwIjoxNjY4Nzk0ODEyfQ.EZNwEwowDKtQBv3zJvv2TPBcgW2ejwe65WjnSlGd-Gs"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "updated_at": "2022-11-19T11:33:11+03:30",
                    "last_status": "DOING"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/task/workertasks/DOING": {
      "get": {
        "tags": [
          "Task Manager"
        ],
        "summary": "GetWorkerTasks",
        "requestBody": {
          "content": {}
        },
        "parameters": [
          {
            "name": "token",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6InNhcmFSQGdtYWlsLmNvbSIsIkZpcnN0X25hbWUiOiJzYXJhIiwiTGFzdF9uYW1lIjoic2FmYWVlIiwiVWlkIjoiNjM1NTNjZmY1MzYxMTNmMjBhOWEyOGFmIiwiVXNlcl9yb2xlIjoiUkVRVUVTVEVSIiwiZXhwIjoxNjY4Nzk0ODEyfQ.EZNwEwowDKtQBv3zJvv2TPBcgW2ejwe65WjnSlGd-Gs"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "total_count": 1,
                    "user_items": [
                      {
                        "_id": "63767830a4ece5e441472975",
                        "alltasks": [
                          {
                            "_id": "6374cb0f28fcffdd26a16180",
                            "approve_on_demand": true,
                            "created_at": "2022-11-16T15:05:43+03:30",
                            "deadline": "2023-10-25T12:25:00+03:30",
                            "description": null,
                            "max_workers": 10,
                            "requester_id": "63553cff536113f20a9a28af",
                            "stream_id": "6374cadd28fcffdd26a1617f",
                            "task_id": "6374cb0f28fcffdd26a16180",
                            "title": "school0",
                            "updated_at": "2022-11-16T15:05:43+03:30",
                            "wage": null
                          }
                        ],
                        "created_at": "2022-11-17T21:36:40+03:30",
                        "last_status": "DOING",
                        "task_id": "6374cb0f28fcffdd26a16180",
                        "updated_at": "0001-01-01T03:30:00+03:30",
                        "worker_id": "63553cec536113f20a9a28ae",
                        "worker_task_id": "63767830a4ece5e441472975"
                      }
                    ]
                  }
                }
              }
            }
          }
        }
      }
    },
    "/stream": {
      "post": {
        "tags": [
          "Stream Manager"
        ],
        "summary": "CtreateStream",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "title": "school",
                  "token": ";k;54654864,knlknsm"
                }
              }
            }
          }
        },
        "parameters": [
          {
            "name": "token",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6InNhcmFSQGdtYWlsLmNvbSIsIkZpcnN0X25hbWUiOiJzYXJhIiwiTGFzdF9uYW1lIjoic2FmYWVlIiwiVWlkIjoiNjM1NTNjZmY1MzYxMTNmMjBhOWEyOGFmIiwiVXNlcl9yb2xlIjoiUkVRVUVTVEVSIiwiZXhwIjoxNjY4Njg0ODU2fQ.5yFyfMShLWWHCmRd9NyfAxC46LIte7Ar4vmRep9ZtX0"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/streams": {
      "get": {
        "tags": [
          "Stream Manager"
        ],
        "summary": "GetStreams",
        "parameters": [
          {
            "name": "token",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6InNhcmFSQGdtYWlsLmNvbSIsIkZpcnN0X25hbWUiOiJzYXJhIiwiTGFzdF9uYW1lIjoic2FmYWVlIiwiVWlkIjoiNjM1NTNjZmY1MzYxMTNmMjBhOWEyOGFmIiwiVXNlcl9yb2xlIjoiUkVRVUVTVEVSIiwiZXhwIjoxNjY4MjY4NDIyfQ.CEw-8oW75l2U9niGX_MopbmQDEeGqvVt_WOMe230Y-c"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/stream/635be6402c641dae109f3e14": {
      "put": {
        "tags": [
          "Stream Manager"
        ],
        "summary": "EditStream",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "title": "855"
                }
              }
            }
          }
        },
        "parameters": [
          {
            "name": "token",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6InNhcmFSQGdtYWlsLmNvbSIsIkZpcnN0X25hbWUiOiJzYXJhIiwiTGFzdF9uYW1lIjoic2FmYWVlIiwiVWlkIjoiNjM1NTNjZmY1MzYxMTNmMjBhOWEyOGFmIiwiVXNlcl9yb2xlIjoiUkVRVUVTVEVSIiwiZXhwIjoxNjY3MDU0MzE1fQ.k9uf0LWGyfBu9gqY8cucp-PNaY5dz33x0WdbdiLWw4A"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/action": {
      "post": {
        "tags": [
          "Stream Manager"
        ],
        "summary": "CtreateAction",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "name": "walking22"
                }
              }
            }
          }
        },
        "parameters": [
          {
            "name": "token",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6InNhcmFSQGdtYWlsLmNvbSIsIkZpcnN0X25hbWUiOiJzYXJhIiwiTGFzdF9uYW1lIjoic2FmYWVlIiwiVWlkIjoiNjM1NTNjZmY1MzYxMTNmMjBhOWEyOGFmIiwiVXNlcl9yb2xlIjoiUkVRVUVTVEVSIiwiZXhwIjoxNjY4MDg3MzYyfQ.kGi-PnmyAM3OTsQOvWsWYnliTvDU0dyInZ6S6QJHfeg"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "put": {
        "tags": [
          "Stream Manager"
        ],
        "summary": "EditAction",
        "requestBody": {
          "content": {}
        },
        "parameters": [
          {
            "name": "token",
            "in": "header",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/action/636bb38594447bae3250a984": {
      "put": {
        "tags": [
          "Stream Manager"
        ],
        "summary": "EditAction",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "name": "running"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/action/636baff61dcbf32489e0f29f": {
      "get": {
        "tags": [
          "Stream Manager"
        ],
        "summary": "GetAction",
        "parameters": [
          {
            "name": "token",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6InNhcmFSMUBnbWFpbC5jb20iLCJGaXJzdF9uYW1lIjoic2FyYSIsIkxhc3RfbmFtZSI6InNhZmFlZSIsIlVpZCI6IjYzNTY0MWNlYWY2YTIxZjQyNTU5OTI5MiIsIlVzZXJfcm9sZSI6IlJFUVVFU1RFUiIsImV4cCI6MTY2ODA4ODIzNH0.KSGU-2xPh6ozWV04Vc6P-h_uiJGarPP_5MKIwaJ0ZRw"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/actions": {
      "get": {
        "tags": [
          "Stream Manager"
        ],
        "summary": "GetActions",
        "parameters": [
          {
            "name": "token",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6InNhcmFSQGdtYWlsLmNvbSIsIkZpcnN0X25hbWUiOiJzYXJhIiwiTGFzdF9uYW1lIjoic2FmYWVlIiwiVWlkIjoiNjM1NTNjZmY1MzYxMTNmMjBhOWEyOGFmIiwiVXNlcl9yb2xlIjoiUkVRVUVTVEVSIiwiZXhwIjoxNjY4MjY4NDIyfQ.CEw-8oW75l2U9niGX_MopbmQDEeGqvVt_WOMe230Y-c"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/action/636bb5ddf5d747285e342aa9": {
      "delete": {
        "tags": [
          "Stream Manager"
        ],
        "summary": "DeleteAction",
        "parameters": [
          {
            "name": "token",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6InNhcmFSQGdtYWlsLmNvbSIsIkZpcnN0X25hbWUiOiJzYXJhIiwiTGFzdF9uYW1lIjoic2FmYWVlIiwiVWlkIjoiNjM1NTNjZmY1MzYxMTNmMjBhOWEyOGFmIiwiVXNlcl9yb2xlIjoiUkVRVUVTVEVSIiwiZXhwIjoxNjY4MDg3MzYyfQ.kGi-PnmyAM3OTsQOvWsWYnliTvDU0dyInZ6S6QJHfeg"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/stream/636e0c1358647128f1d1b620": {
      "delete": {
        "tags": [
          "Stream Manager"
        ],
        "summary": "DeleteStream",
        "parameters": [
          {
            "name": "token",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6InNhcmFSQGdtYWlsLmNvbSIsIkZpcnN0X25hbWUiOiJzYXJhIiwiTGFzdF9uYW1lIjoic2FmYWVlIiwiVWlkIjoiNjM1NTNjZmY1MzYxMTNmMjBhOWEyOGFmIiwiVXNlcl9yb2xlIjoiUkVRVUVTVEVSIiwiZXhwIjoxNjY4MjQwMTg4fQ.RMjbdAz0ZUg2trGAWAchmANUYQ7OuHY3S3S34K-TFWk"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/stream/filter": {
      "post": {
        "tags": [
          "Stream Manager"
        ],
        "summary": "CreateFilterStream",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "stream_id": "636df27f19f1020d7b43e5f1",
                  "action_id": "636bad298b1e5149986e9ad9",
                  "severity": 463
                }
              }
            }
          }
        },
        "parameters": [
          {
            "name": "token",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6InNhcmFSQGdtYWlsLmNvbSIsIkZpcnN0X25hbWUiOiJzYXJhIiwiTGFzdF9uYW1lIjoic2FmYWVlIiwiVWlkIjoiNjM1NTNjZmY1MzYxMTNmMjBhOWEyOGFmIiwiVXNlcl9yb2xlIjoiUkVRVUVTVEVSIiwiZXhwIjoxNjY4NTkzMDg2fQ.WuhENlGFYmQ77QUaxnysQVeAe0eUQX9-UfSQVNl62qk"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/stream/filter/636e70597dcc0029cea67b7b": {
      "get": {
        "tags": [
          "Stream Manager"
        ],
        "summary": "GetFilterStreamByID",
        "parameters": [
          {
            "name": "token",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6InNhcmFSQGdtYWlsLmNvbSIsIkZpcnN0X25hbWUiOiJzYXJhIiwiTGFzdF9uYW1lIjoic2FmYWVlIiwiVWlkIjoiNjM1NTNjZmY1MzYxMTNmMjBhOWEyOGFmIiwiVXNlcl9yb2xlIjoiUkVRVUVTVEVSIiwiZXhwIjoxNjY4MjY4NDIyfQ.CEw-8oW75l2U9niGX_MopbmQDEeGqvVt_WOMe230Y-c"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "put": {
        "tags": [
          "Stream Manager"
        ],
        "summary": "EditFilterStream",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "severity": 2,
                  "action_id": "akfjlaofjs"
                }
              }
            }
          }
        },
        "parameters": [
          {
            "name": "token",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6InNhcmFSQGdtYWlsLmNvbSIsIkZpcnN0X25hbWUiOiJzYXJhIiwiTGFzdF9uYW1lIjoic2FmYWVlIiwiVWlkIjoiNjM1NTNjZmY1MzYxMTNmMjBhOWEyOGFmIiwiVXNlcl9yb2xlIjoiUkVRVUVTVEVSIiwiZXhwIjoxNjY4NTkzMDg2fQ.WuhENlGFYmQ77QUaxnysQVeAe0eUQX9-UfSQVNl62qk"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/stream/filters/636df27f19f1020d7b43e5f1": {
      "get": {
        "tags": [
          "Stream Manager"
        ],
        "summary": "GetFilterStreamsByStreamID",
        "parameters": [
          {
            "name": "token",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6InNhcmFSQGdtYWlsLmNvbSIsIkZpcnN0X25hbWUiOiJzYXJhIiwiTGFzdF9uYW1lIjoic2FmYWVlIiwiVWlkIjoiNjM1NTNjZmY1MzYxMTNmMjBhOWEyOGFmIiwiVXNlcl9yb2xlIjoiUkVRVUVTVEVSIiwiZXhwIjoxNjY4NTkzMDg2fQ.WuhENlGFYmQ77QUaxnysQVeAe0eUQX9-UfSQVNl62qk"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/stream/filter/63736466fffe2de5b8462fe2": {
      "delete": {
        "tags": [
          "Stream Manager"
        ],
        "summary": "DeleteFilterStream",
        "parameters": [
          {
            "name": "token",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6InNhcmFSMUBnbWFpbC5jb20iLCJGaXJzdF9uYW1lIjoic2FyYSIsIkxhc3RfbmFtZSI6InNhZmFlZSIsIlVpZCI6IjYzNTY0MWNlYWY2YTIxZjQyNTU5OTI5MiIsIlVzZXJfcm9sZSI6IlJFUVVFU1RFUiIsImV4cCI6MTY2ODU5NzIyMX0.4WNzBWgbfEfQiIAewF35Qz_9RFckU86FwyBhyB36-S0"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/notification": {
      "post": {
        "tags": [
          "Notification Manager"
        ],
        "summary": "SendNotification",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "message": "a dog ate a sandwich ",
                  "worker_task_id": "6374cb3f28fcffdd26a16181",
                  "notification_type": "REPORT"
                }
              }
            }
          }
        },
        "parameters": [
          {
            "name": "token",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6InNhcmFSQGdtYWlsLmNvbSIsIkZpcnN0X25hbWUiOiJzYXJhIiwiTGFzdF9uYW1lIjoic2FmYWVlIiwiVWlkIjoiNjM1NTNjZmY1MzYxMTNmMjBhOWEyOGFmIiwiVXNlcl9yb2xlIjoiUkVRVUVTVEVSIiwiZXhwIjoxNjY4ODYyMjM2fQ.15Mf6nmAZB177kstU7-5by_VWdxCsQ_brv96EhlKqic"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/notifications/6374cb3f28fcffdd26a16181/SENT": {
      "get": {
        "tags": [
          "Notification Manager"
        ],
        "summary": "GetNotifications",
        "parameters": [
          {
            "name": "token",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6InNhcmFXQGdtYWlsLmNvbSIsIkZpcnN0X25hbWUiOiJzYXJhIiwiTGFzdF9uYW1lIjoic2FmYWVlIiwiVWlkIjoiNjM1NTNjZWM1MzYxMTNmMjBhOWEyOGFlIiwiVXNlcl9yb2xlIjoiV09SS0VSIiwiZXhwIjoxNjY4ODYyMTgwfQ.CS6jlFXQ1BvmBVYf1xdE8NlITE0HYafzUhjPUDXj_9o"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    }
  }
}